### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Yannnnnnnnnnnn** [whatseven/UrbanScene3D#1]
How to use the simulator to capture data in the UE4?

**Comment by whatseven** [comment]
First, it is better to use Airsim to capture data (image, Lidar) in UrbanScene3D. You should download [Airsim](https://microsoft.github.io/AirSim/) and follow the official tutorial to compile it.

Then, you can use C++ or Python to manipulate the agent and get the data you want through [Airsim API](https://microsoft.github.io/AirSim/apis/).

**Comment by Yannnnnnnnnnnn** [comment]
Thanks!
