### ISSUE TITLE
Adding a short "how to" section

### ISSUE THREAD

**Issue by IanCher** [whatseven/UrbanScene3D#2]
Hello!

Thank you very much for releasing this dataset, it is quite an impressive work! I have a couple of questions regarding it:

1. I am not sure how to generate and save the rgb, depth map, calibration and instance segmentation. Is it possible to add a section in the documentation explaining how exactly to use the dataset to generate data? (I have never used Unreal and Airsim).

2. Where can I find the raw data for the real scenes? I downloaded the dataset via FTP and cannot find it (the folder structure is not clear to me).

Best regards!

**Comment by whatseven** [comment]
Sorry for the late reply. I have sent you the link to the raw data.

**Comment by hturki** [comment]
Could I get a link to the raw data as well? Thanks!

**Comment by whatseven** [comment]
> Could I get a link to the raw data as well? Thanks!

Could you leave your email here? I will send you the link to the raw data by email.

**Comment by hturki** [comment]
turki.haithem@gmail.com - thanks!

**Comment by 1612190130** [comment]
Hello, I also want a copy of raw data. b757508036@126.com

**Comment by jlxAha** [comment]
Could I get a link to the raw data as well? Thanks! 1422541026@qq.com

**Comment by Luo1Cheng** [comment]
Hello, thanks for your work. Could you please give me a link to the raw data?  Thanks,~!

**Comment by santolina** [comment]
Hello, thanks for your great work!  May I ask you give me a link to the raw data?
sunny.days@gmail.com

**Comment by saihv** [comment]
@whatseven Hi, I’m also interested in the raw data - could you please send me a link at saihvemprala@gmail.com? Thanks!

**Comment by MiZhenxing** [comment]
@whatseven Hi, could you send me the link of the raw data at zmiaa@connect.ust.hk ? Many thanks!

**Comment by asedfrgt** [comment]
@whatseven Hi, could you send me the link of the raw data at [m201572441@alumni.hust.edu.cn](mailto:m201572441@alumni.hust.edu.cn)? Many thanks!

**Comment by zyqz97** [comment]
Hi, could you send me the link of the raw data at [zhangyuqi@nuaa.edu.edu.cn](mailto:m201572441@alumni.hust.edu.cn)? Many thanks!

**Comment by whatseven** [comment]
The official website for UrbanScene3D has moved to https://vcc.tech/UrbanScene3D. You could find all the resources on this website.

**Comment by sjtuytc** [comment]
@whatseven Can you send me the raw data at sjtuytc@gmail.com? I don't find the exact link to the real-world images.

**Comment by yilinliu77** [comment]
> @whatseven Can you send me the raw data at [sjtuytc@gmail.com](mailto:sjtuytc@gmail.com)? I don't find the exact link to the real-world images.

Sorry, I no longer maintain the download link now. You can find the link to images under the "Path + image" section on the official website.

**Comment by ventusff** [comment]
Hi @yilinliu77 , 
Currently the official website's "Path + image" contains multiple choices of path+image combination. Which of them corresponds to the provided refined camera poses in this repo ?
In the download links from the official website there are 10 choices of path+image zip files, e.g. "Oblique Photography", "Smith et al." 2018 x [coarse, inter, fine], "Zhou et al" x [coarse, inter, fine], "Zhang et al" x [coarse, inter, fine]

**Comment by saihv** [comment]
@yilinliu77 Hi, could you please clarify how to download the city scenes (New York, San Francisco etc.)? The website links to the data only seem to contain the smaller scenes like School, Bridge, Castle etc.
