### ISSUE TITLE
Error while dataset download

### ISSUE THREAD

**Issue by SarveshRobotics** [whatseven/UrbanScene3D#3]
Hi,
I am trying to download the dataset through the Dropbox link. I am individually downloading each zip file containing the video. It downloads fine, but during extraction it fails. Reports error : Error while extracting video '...mp4'. When I run these partial extracted videos, they only run through few minutes of the total length.

Please help in resolving this.

Best,
Sarvesh

**Comment by whatseven** [comment]
What do you mean by "downloading each zip file containing the video"? You need to download all the zip files and extract the main document.

Or you might try to use the HTTP or FTP link to download the whole file directly.

**Comment by whatseven** [comment]
Besides the video, do other files go right? The video is compressed together with other files. You need to extract them all together.
