### ISSUE TITLE
hardware configuration requirement

### ISSUE THREAD

**Issue by pawnjiang** [whatseven/UrbanScene3D#4]
I want to know what kind of hardware configuration is required to run airsim for deep reinforcement learning in your scenario
在这个场景中用airsim做深度强化学习需要什么配置呢，或者你们使用的服务器配置是什么呢

**Comment by whatseven** [comment]
Hello, sorry for the late reply. 

We are using RTX 4000 GPU for our data collection. We haven't tested the RL algorithm on our computer. But I think you should have a big RAM (>16G) to deal with the real scene since they are usually very big (the raw obj mesh is larger than 4GB).
