### ISSUE TITLE
Version of Unreal used for Simulator

### ISSUE THREAD

**Issue by chinmaychinara91** [whatseven/UrbanScene3D#5]
Hi,

I downloaded the simulator from https://vcc.tech/UrbanScene3D but it seems it was not made with Unreal 4.24 (as stated in the gitub page) but rather a newer version. Can I know what version of Unreal it is built on?

**Comment by yilinliu77** [comment]
Hi,

Please refer to this issue and see if it works: https://github.com/Linxius/UrbanScene3D/issues/7

**Comment by chinmaychinara91** [comment]
UE 4.27.2 with VS 2022 worked for me. Thanks.
